### ISSUE TITLE
'bin2ea not found'

### ISSUE THREAD

**Issue by boviex** [StanHash/FE-CHAX#1]
tried to use it on the CCB round 1 buildfile and got this error:
`/github/ccb_round1\Text:Install Text Data.event(7)] ERROR - directive "incext" failed - binary tool ('bin2ea') couldn't be found`

PS can confirm removing `mono` works on windows
PPS come baaack

**Comment by StanHash** [comment]
Put [`bin2ea`](https://github.com/StanHash/bin2ea) in the tools folder of EA; I have described why you need it in [the `pea` README](https://github.com/StanHash/pea-preprocessor/blob/master/README.md); I'll note it here too.

(Also :soon: )
