### ISSUE TITLE
#incext png2dmp w/ --lz77 error

### ISSUE THREAD

**Issue by boviex** [StanHash/FE-CHAX#2]
```
ERROR - directive "incext" failed - failed to scan:
        #incext Png2Dmp "bin/Warning_and_HPGraphic - Copy.png" --lz77
                                                               ^
        expected valid tool argument
```

Doesn't recognize the option?

**Comment by StanHash** [comment]
ugh this time its my fault :/

try with [this build of `pea`](https://github.com/StanHash/FE-CHAX/files/1739942/pea.zip).

Also thank you for showing interest in this :)

**Comment by boviex** [comment]
Fixd yeet

Still got some other issues but I think they're on my end

(be easier if you were on discord reee)
